# 消费CubeUniverseFS的PVC的标准模板，用于在控制台上创建新的pvc。请勿修改或直接部署！！
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc
  namespace: sample-namespace
  labels:
    pvc-provider: cubeuniverse
    pvc-type: filesystem
    auto-scale: auto
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cubeuniverse-fs-storage