apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: cubeuniverse-object
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cubeuniverse-obj-storage
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: cubeuniverse-object
  objectStoreNamespace: rook-ceph
allowVolumeExpansion: true



