apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-backend
  namespace: cubeuniverse
spec:
  selector:
    matchLabels:
      app: cubeuniverse
  replicas: 2
  template:
    metadata:
      labels:
        app: cubeuniverse
        component: control-backend
        status: not-ready
    spec:
      serviceAccountName: universe-account
      containers:
        - name: control-backend
          image: tksky1/cubeuniverse-backend:0.1alpha  # 发布版本
          #image: backend-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 30401
---
apiVersion: v1
kind: Service
metadata:
  name: control-backend
  namespace: cubeuniverse # namespace:cluster
  labels:
    app: control-backend
spec:
  ports:
    - name: dashboard
      port: 30401
      protocol: TCP
      targetPort: 30401
      nodePort: 30401
  selector:
    component: control-backend
    status: ready
  sessionAffinity: None
  type: NodePort