# deployment: CubeUniverse 请使用本文件部署CubeUniverse
# 会自动检测集群健康状况 如果集群符合条件则自动启动UniverseBuilder构建存储系统
---
apiVersion: v1
kind: Namespace
metadata:
  name: cubeuniverse
  labels:
    app: cubeuniverse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: universe-account
  namespace: cubeuniverse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: universe-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: universe-account
    namespace: cubeuniverse
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cubeuniverse-prepare
  namespace: cubeuniverse
spec:
  template:
    spec:
      containers:
        - name: cubeuniverse-prepare
          #image: tksky1/cubeuniverse:dev0.1  # 发布版本
          image: main-dev
          imagePullPolicy: Never #调试完成后这里应该改成IfNotPresent
      serviceAccount: universe-account
      restartPolicy: OnFailure
  backoffLimit: 4
