apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: cubeuniverse
  labels:
    app: cubeuniverse
spec:
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
  selector:
    component: kafka