apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubeuniverse-kafka
  namespace: cubeuniverse
spec:
  selector:
    matchLabels:
      app: cubeuniverse
      component: kafka
  replicas: 2
  template:
    metadata:
      labels:
        app: cubeuniverse
        component: kafka
    spec:
      containers:
        - name: kafka
          image: zhaidea/kafka
          imagePullPolicy: Always #调试完成后  这里应该改成IfNotPresent
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: cubeuniverse
  labels:
    app: cubeuniverse
spec:
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
  selector:
    component: kafka