apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubeuniverse-kafka
  namespace: cubeuniverse
spec:
  selector:
    matchLabels:
      app: cubeuniverse
      component: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: cubeuniverse
        component: kafka
    spec:
      containers:
        - name: kafka
          image: zhaidea/kafka
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
