apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubeuniverse-ml
  namespace: cubeuniverse
spec:
  selector:
    matchLabels:
      app: cubeuniverse
      component: ml
  replicas: 1
  template:
    metadata:
      labels:
        app: cubeuniverse
        component: ml
    spec:
      containers:
        - name: ml
          image: zhaidea/cubeml
          imagePullPolicy: Always