# deployment: UniverseBuilder 组件自动部署程序
# 自动部署CubeUniverse相关组件，由主程序入口调用，请勿直接部署
---
apiVersion: batch/v1
kind: Job
metadata:
  name: universe-builder
  namespace: cubeuniverse
spec:
  template:
    spec:
      containers:
        - name: universe-builder
          image: tksky1/cubeuniverse-builder:0.1alpha  # 发布版本
          #image: builder-dev
          imagePullPolicy: Always
      serviceAccountName: universe-account
      restartPolicy: Never
  backoffLimit: 4
