apiVersion: apps/v1
kind: Deployment
metadata:
  name: universe-operator
  namespace: cubeuniverse
spec:
  selector:
    matchLabels:
      app: cubeuniverse
      component: operator
  replicas: 2
  template:
    metadata:
      labels:
        app: cubeuniverse
        component: operator
    spec:
      serviceAccount: universe-account
      containers:
        - name: operator
          #image: tksky1/cubeuniverse-operator:dev0.1  # 发布版本
          image: operator-dev
          imagePullPolicy: Never #调试完成后  这里应该改成IfNotPresent
          ports:
            - containerPort: 30402
---
apiVersion: v1
kind: Service
metadata:
  name: object-storage
  namespace: cubeuniverse # namespace:cluster
  labels:
    app: operator
spec:
  ports:
    - name: dashboard
      port: 8890
      protocol: TCP
      targetPort: 8890
      nodePort: 30402
  selector:
    component: operator
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: oss
  namespace: cubeuniverse # namespace:cluster
  labels:
    app: operator
spec:
  ports:
    - name: dashboard
      port: 8890
      protocol: TCP
  selector:
    component: operator
  sessionAffinity: None