server:
  port: 8888

datasource:
  driverName: mysql
  host: mysql-in-cluster.cubeuniverse.svc.cluster.local
  port: 3306
  database: cubeuniverse
  username: root
  password: cubeuniverse
  charset: utf8