server:
  port: 30401

datasource:
  driverName: postgres
  host: postgres.cubeuniverse.svc.cluster.local
  port: 5432
  database: cubeuniverseDB
  defaultdatabase: userDB
  username: cubeuniverse
  password: cubeuniverse
  charset: utf8